#!/bin/bash
#Author Ray Fresco Gumti

echo "This tool will REBOOT an instance based on the resource Name Tag"
echo ""
read -p "Which AWS instance would you like to REBOOT?: " INSTANCE

getInstanceID()
{
aws ec2 describe-instances --filters "Name=tag:Name,Values=$1" --query 'Reservations[].Instances[].InstanceId' --output text
}

INSTANCE_ID=$(getInstanceID $INSTANCE)

if [ $(echo $INSTANCE_ID | grep -c  "^i-") -eq 1 ]; then
	aws ec2 reboot-instances --instance-ids $INSTANCE_ID
	aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[].Instances[].State[].Name' --output text

else
	echo "Instance $INSTANCE does not exist"

fi
